### PR TITLE
Add tag values to update-test-group.sh

### PR DESCRIPTION
**Pull request by mcamou**
`Change-type: minor`

### CODE REVIEW

**Comment by thgreasi** [comment]
Hi,
Thanks for your contribution on this.
Could you add `Change-type: minor` in the description of your commit, so that the `ResinCI/check-versionist/versionist` passes as well?
That's required since at Balena we follow some commit guidelines so that our CI system can reason about our PRs.
Thanks again for this :+1:

**Comment by mcamou** [comment]
@thgreasi is this what you mean? Or is it in the commit title?

**Comment by thgreasi** [comment]
@mcamou this the description of the PR. We instead need you to modify the description of the git commit.
You can update the commit message by checking out your branch and doing
```
git commit --amend -m "Add tag values to update-test-group.sh" -m "Change-type: minor"
```
followed by a forced git push.

After doing this change, when you do `git log`, your top commit should look like this:
```
commit a2033474c485059309d4e1c7897467ff75c75613 (HEAD -> add-tag-values)
Author: <YOU>
Date:   <DATE>

    Add tag values to update-test-group.sh
    
    Change-type: minor

```

**Comment by mcamou** [comment]
Thanks for your very clear explanation @thgreasi. It's done.

**Comment by thgreasi** [comment]
Just a small code change and this is good to merge :+1:

**Comment by mcamou** [comment]
Thanks for your comments @thgreasi. I've pushed some changes, see if you like what you see.

**Comment by thgreasi** [comment]
@mcamou thanks for your contribution on this :+1:

**Pull request merged**
